### ISSUE TITLE
Exception in thread "main" java.lang.VerifyError: Cannot inherit from final class

### ISSUE THREAD

**Issue by hshyamh4** [square/keywhiz#101]
Please help me,
I tried with some test classes,but i am unable to retrieve the secrete,

Application.java
--------------------
public class Application {

           public static void main(String[] args) throws IOException {
		OkHttpClient client = mutualSslClient();
		Request.Builder b = new Request.Builder().url("https://localhost:4444");
		Request get = b.get().url("/secret/General_Password").build();
		Response response = client.newCall(get).execute();
		System.out.println(response.code());
	}

	public static OkHttpClient mutualSslClient() {
		String password = "ponies";
		KeyStore keyStore = keyStoreFromResource("clients/client.p12", password);
		KeyStore trustStore = keyStoreFromResource(
				"dev_and_test_truststore.p12", password);

		return HttpClients
				.builder()
				.withClientCert(keyStore, password)
				.addRequestInterceptors(
						new AuthHelper.AcceptRequestInterceptor(
								MediaType.APPLICATION_JSON))
				.build(trustStore, 4445);
	}

	private static KeyStore keyStoreFromResource(String path, String password) {
		KeyStore keyStore;
		try (InputStream stream = Resources.getResource(path).openStream()) {
			keyStore = KeyStore.getInstance("PKCS12");
			keyStore.load(stream, password.toCharArray());
		} catch (IOException | NoSuchAlgorithmException | CertificateException
				| KeyStoreException e) {
			throw new AssertionError(e);
		}
		return keyStore;
	}
}

Then i am getting ,

Exception in thread "main" java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.cybermoney.keywhiz.Application1.mutualSslClient(Application1.java:36)
	at com.cybermoney.keywhiz.Application1.main(Application1.java:22)

**Comment by sul3n3t** [comment]
It's unclear what you're doing from the code snippet provided, but this is not an error in Keywhiz.
