### ISSUE TITLE
Error using db-seed data

### ISSUE THREAD

**Issue by joffotron** [square/keywhiz#125]
I'm trying to get a basic test setup running, so far, I've built a Docker image, and run the migrations:

`docker run -p 4444:4444 square/keywhiz java -jar server/target/keywhiz-server-0.7.5-shaded.jar migrate server/src/main/resources/keywhiz-development.yaml`

Which seems to have worked. However when I try and load the seed data, I get:

```java
docker run -p 4444:4444 square/keywhiz java -jar server/target/keywhiz-server-0.7.5-shaded.jar db-seed server/src/main/resources/keywhiz-development.yaml

...

Exception in thread "main" org.jooq.exception.DataAccessException: SQL [insert into GROUPS (ID, NAME, CREATEDAT, UPDATEDAT) values (cast(? as int), cast(? as varchar), cast(? as timestamp), cast(? as timestamp)), (cast(? as int), cast(? as varchar), cast(? as timestamp), cast(? as timestamp)), (cast(? as int), cast(? as varchar), cast(? as timestamp), cast(? as timestamp)), (cast(? as int), cast(? as varchar), cast(? as timestamp), cast(? as timestamp)), (cast(? as int), cast(? as varchar), cast(? as timestamp), cast(? as timestamp))]; Table "GROUPS" not found; SQL statement:
insert into GROUPS (ID, NAME, CREATEDAT, UPDATEDAT) values (cast(? as int), cast(? as varchar), cast(? as timestamp), cast(? as timestamp)), (cast(? as int), cast(? as varchar), cast(? as timestamp), cast(? as timestamp)), (cast(? as int), cast(? as varchar), cast(? as timestamp), cast(? as timestamp)), (cast(? as int), cast(? as varchar), cast(? as timestamp), cast(? as timestamp)), (cast(? as int), cast(? as varchar), cast(? as timestamp), cast(? as timestamp)) [42102-187]
	at org.jooq.impl.Utils.translate(Utils.java:1645)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:661)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:356)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:133)
	at keywhiz.commands.DbSeedCommand.doImport(DbSeedCommand.java:89)
	at keywhiz.commands.DbSeedCommand.run(DbSeedCommand.java:71)
	at keywhiz.commands.DbSeedCommand.run(DbSeedCommand.java:51)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:73)
	at keywhiz.KeywhizService.main(KeywhizService.java:83)
Caused by: org.h2.jdbc.JdbcSQLException: Table "GROUPS" not found; SQL statement:
insert into GROUPS (ID, NAME, CREATEDAT, UPDATEDAT) values (cast(? as int), cast(? as varchar), cast(? as timestamp), cast(? as timestamp)), (cast(? as int), cast(? as varchar), cast(? as timestamp), cast(? as timestamp)), (cast(? as int), cast(? as varchar), cast(? as timestamp), cast(? as timestamp)), (cast(? as int), cast(? as varchar), cast(? as timestamp), cast(? as timestamp)), (cast(? as int), cast(? as varchar), cast(? as timestamp), cast(? as timestamp)) [42102-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readTableOrView(Parser.java:5261)
	at org.h2.command.Parser.readTableOrView(Parser.java:5238)
	at org.h2.command.Parser.parseInsert(Parser.java:1031)
	at org.h2.command.Parser.parsePrepared(Parser.java:401)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:72)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:277)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
	at com.sun.proxy.$Proxy30.prepareStatement(Unknown Source)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:112)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:76)
	at org.jooq.impl.AbstractQuery.prepare(AbstractQuery.java:394)
	at org.jooq.impl.AbstractDMLQuery.prepare(AbstractDMLQuery.java:192)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:316)
	... 8 more
```

I assume I need this to at least populate the default user for the web ui? It seems like I'm missing a setup step in there somewhere?

**Comment by sul3n3t** [comment]
I was able to get those two commands to work in sequence (albeit not in a container). I checked out the `v0.7.5` tag, ran `mvn package -Ph2`, then the migrate and db-seed commands you invoked.

Would you try to `rm /tmp/h2_data/*` within the container and re-run `migrate` then `db-seed` commands? What was the command you used to for `mvn package ...`?

**Comment by joffotron** [comment]
Thanks @sul3n3t, I think the reason it worked for you out of the container (and the reference to /tmp/h2_data) made it click for me!

I needed to specify a Docker persistent volume for the h2_data:

e.g. 
```
mkdir /tmp/h2_data
docker run -v /tmp/h2_data:/tmp/h2_data -p 4444:4444 square/keywhiz java -jar ... migrate ... etc
```

Then results from the migrate weren't lost before it tried to do the db-seed :-)

I think you can specify the persistent volume in the Docker file (e.g. VOLUME /tmp/h2_data).

I'll do a PR for the docs once I have my head more around it .
