### ISSUE TITLE
cli doesn't build on windows

### ISSUE THREAD

**Issue by klauern** [square/keywhiz#148]
My guess is that the entire project isn't compatible with Windows, but at least from the start, when I run `mvn clean verify` from the parent, I get an error in the `cli` module.  Going in to that module specifically and running `mvn clean verify` produces the following output on my machine (Win7, jdk1.8.0_60+JCE):

```powershell
C:\Users\Me\dev\java\keywhiz\cli [master ≡]
λ mvn clean verify
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Keywhiz CLI 0.7.9-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ keywhiz-cli ---
[INFO] Deleting C:\Users\Me\dev\java\keywhiz\cli\target
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-unlimited-crypto-policy) @ keywhiz-cli ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ keywhiz-cli ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ keywhiz-cli ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ keywhiz-cli ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 22 source files to C:\Users\Me\dev\java\keywhiz\cli\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ keywhiz-cli ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ keywhiz-cli ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 9 source files to C:\Users\Me\dev\java\keywhiz\cli\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.14.1:test (default-test) @ keywhiz-cli ---
[INFO] Surefire report directory: C:\Users\Me\dev\java\keywhiz\cli\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running keywhiz.cli.commands.AddActionTest
2015-11-04 21:05:01,799 - Creating secret 'newSecret' with version '1576915baeb123e0'.
2015-11-04 21:05:01,837 - Creating group 'newGroup'.
2015-11-04 21:05:01,844 - Creating secret 'newSecret' with version '1576915bc725a9a1'.
2015-11-04 21:05:01,850 - Creating client 'newClient'.
2015-11-04 21:05:01,868 - Creating secret 'newSecret' with version '1576915bcdfd8e14'.
2015-11-04 21:05:01,880 - Creating secret 'newSecret' with version ''.
2015-11-04 21:05:01,905 - Creating secret 'newSecret' with version '1576915bdc6dc6b4'.
2015-11-04 21:05:01,906 - Allowing group 'newGroup' access to secret 'newSecret'.
2015-11-04 21:05:01,914 - Creating secret 'newSecret' with version '1576915bea18e06a'.
Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.397 sec
Running keywhiz.cli.commands.AssignActionTest
2015-11-04 21:05:01,943 - Creating client 'non-existent-client-name'.
2015-11-04 21:05:01,944 - Enrolling client 'non-existent-client-name' in group 'group'.
2015-11-04 21:05:01,947 - Enrolling client 'existing-client-name' in group 'group'.
2015-11-04 21:05:01,951 - Allowing group 'group' access to secret 'secret'.
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec
Running keywhiz.cli.commands.DeleteActionTest
Please confirm deletion of secret 'secret': Y/N
Please confirm deletion of secret 'secret': Y/N
Please confirm deletion of secret 'secret': Y/N
2015-11-04 21:05:01,965 - Deleting group 'Web'.
2015-11-04 21:05:01,976 - Deleting client 'newClient'.
Please confirm deletion of secret 'secret': Y/N
2015-11-04 21:05:01,978 - Deleting secret 'secret'.
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 sec
Running keywhiz.cli.commands.DescribeActionTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec
Running keywhiz.cli.commands.ListActionTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running keywhiz.cli.commands.UnassignActionTest
2015-11-04 21:05:02,079 - Evicting client 'client-name' from group 'group-name'.
2015-11-04 21:05:02,081 - Revoke group 'group-name' access to secret 'secret-name..1576915c401e87fb'.
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
Running keywhiz.cli.JsonCookieTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.129 sec
Running keywhiz.cli.UtilitiesTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running keywhiz.client.ClientUtilsTest
Tests run: 6, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.869 sec <<< FAILURE!
testLoadCookiesWithFile(keywhiz.client.ClientUtilsTest)  Time elapsed: 0.022 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/Me/dev/java/keywhiz/cli/target/test-classes/fixtures/cookies.json
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at keywhiz.client.ClientUtilsTest.testLoadCookiesWithFile(ClientUtilsTest.java:129)

testSaveAndLoadCookies(keywhiz.client.ClientUtilsTest)  Time elapsed: 0.054 sec  <<< ERROR!
java.lang.UnsupportedOperationException: null
        at java.nio.file.Files.setPosixFilePermissions(Files.java:2044)
        at keywhiz.cli.ClientUtils.saveCookies(ClientUtils.java:131)
        at keywhiz.client.ClientUtilsTest.testSaveAndLoadCookies(ClientUtilsTest.java:138)

testSaveCookies(keywhiz.client.ClientUtilsTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.UnsupportedOperationException: null
        at java.nio.file.Files.setPosixFilePermissions(Files.java:2044)
        at keywhiz.cli.ClientUtils.saveCookies(ClientUtils.java:131)
        at keywhiz.client.ClientUtilsTest.testSaveCookies(ClientUtilsTest.java:113)


Results :

Tests in error:
  ClientUtilsTest.testLoadCookiesWithFile:129 » InvalidPath Illegal char <:> at ...
  ClientUtilsTest.testSaveAndLoadCookies:138 » UnsupportedOperation
  ClientUtilsTest.testSaveCookies:113 » UnsupportedOperation

Tests run: 70, Failures: 0, Errors: 3, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.749 s
[INFO] Finished at: 2015-11-04T15:05:03-06:00
[INFO] Final Memory: 46M/369M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.14.1:test (default-test) on project keywhiz-cli: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Me\dev\java\keywhiz\cli\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by klauern** [comment]
This StackOverflow answer points to one of the issues: http://stackoverflow.com/q/9834776/7008

However, I think that [this line](https://github.com/square/keywhiz/blob/ef13867b4cfd28dfcf6f10fd44e332d889a72d07/cli/src/main/java/keywhiz/cli/ClientUtils.java#L131) is also troubling, so I don't think it's as simple as substituting in the following:

```java
private static final boolean IS_WINDOWS = System.getProperty( "os.name" ).contains( "indow" );

...

    String cookiePath = Resources.getResource("fixtures/cookies.json").getPath();
    if (IS_WINDOWS) {
        cookiePath = cookiePath.substring(1);
    }
    Path savedCookies = Paths.get(cookiePath);
    List<HttpCookie> loadedCookies = ClientUtils.loadCookies(savedCookies);
```

**Comment by mcpherrinm** [comment]
The code does have a few issues that prevent it from working on Windows, but it's nothing major -- I've got a hacked up copy somewhere that does work.  Do you just care about the Cli working on Windows, or are you interested in running the server, too?

I suspect the filesystem will never work on Windows, either, so you'd need a different client there, if you're anticipating using Keywhiz in an all-windows environment.

**Comment by klauern** [comment]
I think getting the CLI working on Windows would be okay for my use.  I'm really looking to evaluate it, and starting with the `keywhiz-parent` didn't build successfully on my work laptop.

I suspect once I get a better feel for how it would be used, I might have more concerns or questions, but for now, I'll shoot for building it on one of our *nix environments and see how it goes.

**Comment by mcpherrinm** [comment]
I'll push my Windows experiments to a branch on Github when I get a chance -- should be within 48 hours.  Please feel free to let me know about any problems you run into -- there's probably some sharp corners and missing docs.

**Comment by mcpherrinm** [comment]
https://github.com/mcpherrinm/keywhiz/tree/mmc/windows-cli

This branch contains some hacky changes that get the Cli to mostly work.  I'll try to get the server to build soon.

**Comment by klauern** [comment]
I was able to get that branch built, but I had to make a change: mcpherrinm/keywhiz#1

**Comment by alokmenghrajani** [comment]
I'm going to close this issue. I think building from https://github.com/mcpherrinm/keywhiz/commits/mmc/windows-cli is a viable solution for now.

@klauern: feel free to submit a PR which builds on both unix and windows. Making the pom.xml changes conditional might require some work but should be doable.
