### ISSUE TITLE
Is docker image usable to test the setup locally? 

### ISSUE THREAD

**Issue by sureshg** [square/keywhiz#320]
Tried to build it on mac and it errors out on server with H2 errors. I know keywhiz is focussed on mysql, but this docker image is pretty handy for doing a quick test.

```getClientsForGroup(keywhiz.service.daos.AclDAOTest)  Time elapsed: 0.003 sec  <<< ERROR!
org.jooq.exception.DataAccessException: SQL [insert into CLIENTS (NAME, CREATEDAT, UPDATEDAT, DESCRIPTION, CREATEDBY, UPDATEDBY, ENABLED, AUTOMATIONALLOWED, LASTSEEN) values (cast(? as varchar), cast(? as timestamp), cast(? as timestamp), cast(? as varchar), cast(? as varchar), cast(? as varchar), cast(? as boolean), cast(? as boolean), cast(? as timestamp))]; Unique index or primary key violation: "CONSTRAINT_5E_INDEX_B ON PUBLIC.CLIENTS(NAME) VALUES ('client1', 1)"; SQL statement:
insert into CLIENTS (NAME, CREATEDAT, UPDATEDAT, DESCRIPTION, CREATEDBY, UPDATEDBY, ENABLED, AUTOMATIONALLOWED, LASTSEEN) values (cast(? as varchar), cast(? as timestamp), cast(? as timestamp), cast(? as varchar), cast(? as varchar), cast(? as varchar), cast(? as boolean), cast(? as boolean), cast(? as timestamp)) [23505-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:102)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:233)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:191)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:638)
	at org.h2.command.dml.Insert.insertRows(Insert.java:156)
	at org.h2.command.dml.Insert.update(Insert.java:114)
```

```[INFO] Keywhiz (Parent) ................................... SUCCESS [ 20.531 s]
[INFO] Keywhiz Testing .................................... SUCCESS [ 17.471 s]
[INFO] Keywhiz API ........................................ SUCCESS [  6.875 s]
[INFO] Keywhiz Client ..................................... SUCCESS [  1.031 s]
[INFO] Keywhiz CLI ........................................ SUCCESS [ 10.973 s]
[INFO] Keywhiz HKDF ....................................... SUCCESS [  1.025 s]
[INFO] Keywhiz Model ...................................... SUCCESS [  7.076 s]
[INFO] Keywhiz Log ........................................ SUCCESS [  0.203 s]
[INFO] Keywhiz Server ..................................... FAILURE [01:37 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:43 min
[INFO] Finished at: 2017-03-20T21:20:10+00:00
[INFO] Final Memory: 109M/292M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.14.1:test (default-test) on project keywhiz-server: There are test failures.
[ERROR]
[ERROR] Please refer to /usr/src/app/server/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :keywhiz-server
Removing intermediate container 0960a741f0c4
The command '/bin/sh -c mvn install -P docker' returned a non-zero code: 1```

**Comment by bseb** [comment]
@sureshg I had the same issue, starting docker-machine seems to allow the container to build/run normally

**Comment by mbyczkowski** [comment]
I believe this problem has been fixed since. Most recently, though, we have dropped H2 in favor of using MySQL-only in dev and docker container (#444).
