### ISSUE TITLE
Examples don't work out of the box

### ISSUE THREAD

**Issue by daniellockard** [square/keywhiz#42]
Keywhiz server and CLI compile fine, and I can log in to the webui with both a user from the development sample SQL and a user I added my self in the database. However I can't seem to use keywhiz.cli to log in. 

```bash
danny@MacBook-Pro ~/src/keywhiz ±master » ./cli/target/keywhiz-cli-*-SNAPSHOT-shaded.jar -U https://localhost:4444/ login      130 ↵
password for 'danny':
Exception in thread "main" javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1917)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:301)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:295)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1369)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:156)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:925)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:860)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1043)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
	at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:241)
	at com.squareup.okhttp.Connection.connect(Connection.java:158)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:174)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:131)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:312)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:235)
	at com.squareup.okhttp.Call.getResponse(Call.java:262)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at keywhiz.client.KeywhizClient.httpPost(KeywhizClient.java:272)
	at keywhiz.client.KeywhizClient.login(KeywhizClient.java:111)
	at keywhiz.cli.CommandExecutor.executeCommand(CommandExecutor.java:121)
	at keywhiz.cli.CliMain.main(CliMain.java:68)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1351)
	... 22 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 28 more
```

This is a 100% stock server with just the development user and my "danny" user added. I'm assuming this is because the certificate i'm testing with it not actually signed by a trusted root CA?

It also seems there is little-to-no documentation around actually adding your own CA to the server. I believe this would live in "derivation.jceks" but i'm not sure. 

Any guidance as to how one would actually use keywhiz in production would be greatly appreciated. I'm working on secrets management right now, and keywhiz seems to be the 'answer' to that if I can make it work in production.

**Comment by sul3n3t** [comment]
Hmm, yeah that's correct. The development (and test) CAs are not trusted by the JRE out-of-the-box and they shouldn't be. If we add an optional `--cafile` argument to keywhiz.cli, I think that would solve your initial problem.

Regarding configuration changes for a real deployment, I think a github wiki page would be good to explain that. Without going into detail that would be on the wiki page, going through a configuration file and changing authentication and cryptography values is enough (keyStorePath, keyStorePassword, trustStorePath, trustStorePassword, database host & authentication, cookieKey, and derivation keystore. The wiki page can say how to generate things like the derivation key.

**Comment by alokmenghrajani** [comment]
Do you know why `java -Djavax.net.ssl.keyStore=server/src/main/resources/dev_and_test_truststore.jceks -Djavax.net.ssl.keyStorePassword=ponies -jar cli/target/keywhiz-cli-0.7.4-SNAPSHOT-shaded.jar -U https://localhost:4444/ list clients` fails with `sun.security.provider.certpath.SunCertPathBuilderException`?

**Comment by sherzberg** [comment]
@alokmenghrajani I had to also add `-Djavax.net.ssl.trustStoreType=JCEKS` but now I'm hitting `Hostname XXXX not verified`.

**Comment by sherzberg** [comment]
To elaborate on my last comment, I am also trying to get the docs examples setup.

I should just generate my own keystore and truststores, but I'd like the get this all working from the current docs.

This is my current stumbling block:

```bash
$ java -Djavax.net.ssl.trustStore=server/src/main/resources/dev_and_test_truststore.jceks -Djavax.net.ssl.trustStorePassword=ponies -Djavax.net.ssl.trustStoreType=JCEKS -Dweblogic.security.SSL.ignoreHostnameVerification=true -jar cli/target/keywhiz-cli-0.7.4-SNAPSHOT-shaded.jar login                          
password for 'spencerherzberg': 
Exception in thread "main" java.io.IOException: Hostname spencerherzberg-mbp not verified:
    certificate: sha1/gLY+RwEEV8DOuhNhKGf02+u/fRk=
    DN: OU=keywhiz, CN=*
    subjectAltNames: []
        at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:260)
        at com.squareup.okhttp.Connection.connect(Connection.java:158)
        at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:174)
        at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
        at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:131)
        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:312)
        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:235)
        at com.squareup.okhttp.Call.getResponse(Call.java:262)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
        at com.squareup.okhttp.Call.execute(Call.java:79)
        at keywhiz.client.KeywhizClient.httpPost(KeywhizClient.java:272)
        at keywhiz.client.KeywhizClient.login(KeywhizClient.java:111)
        at keywhiz.cli.CommandExecutor.executeCommand(CommandExecutor.java:119)
        at keywhiz.cli.CliMain.main(CliMain.java:68)
```

Any ideas?

**Comment by alokmenghrajani** [comment]
That makes more sense. I'm testing with a cert which has localhost instead of "*" for the CN.

**Comment by sherzberg** [comment]
I got a newly created keystore and truststore working just fine. I had to use the exact hostname of the client connecting to get it to work. But, I would still like to figure out the dev_and_test keystores to work out of the box.

**Comment by alokmenghrajani** [comment]
Just wanted to post a short note saying that this is still something we want to fix and that this issue hasn't been forgotten.

**Comment by sul3n3t** [comment]
I've merged some new key material for dev_and_test to master. The process is documented on a [wiki page](https://github.com/square/keywhiz/wiki/Development-and-test-key-material). The new server certificate is valid for __localhost__, so that should resolve the hostname verification problem out-of-the-box.

Pending issues are:
- [ ] Keywhiz CLI supports `--username` flag: https://github.com/square/keywhiz/issues/64
- [ ] Keywhiz CLI instructions for specifying truststore: https://github.com/square/keywhiz/issues/65

**Comment by dragonndev** [comment]
I've created a custom CA setup using Certstrap. Got the keystore & truststore configured and the server starts up fine. I can browse the web UI, etc. 

To address the missing --cafile option for the CLI, I launch the CLI using a custom trust store with Java (e.g. java -Djavax.net.ssl.trustStore=<truststore> -Djavax.net.ssl.trustStorePassword=<password> -jar cli/target/keywhiz-cli-0.7.4-SNAPSHOT-shaded.jar --url https://<host>:4444 login). I've verified the server cert has a CN that matches the hostname used.

However it still throws the exception:
Exception in thread "main" java.io.IOException: Hostname <host> not verified:


Is something special being done that would cause Java to ignore the specified truststore?

**Comment by sul3n3t** [comment]
What if you use `--url https://localhost:4444`?

**Comment by dragonndev** [comment]
I've not tried connecting locally. I'm running in a VM and was connecting from another host. I'll give localhost a try and see if that works.

**Comment by dragonndev** [comment]
Running the same command, but using localhost allows me to login to the CLI.

**Comment by Uxito-Ada** [comment]
I‘ve tried add --user and --devTrustStore flags to the cli, but it doesn't work.
